### ISSUE TITLE
Circular up/down arrows

### ISSUE THREAD

**Issue by kseistrup** [jansc/ncgopher#1]
It would ease navigation if the up/down arrow keys operated as if they were traversing a circular list, such that _cursor up_ would take you to the last link on the page when the cursor is over the first link, and, conversely, the _cursor down_ key would take you from the last link to the first link.

**Comment by jansc** [comment]
Improving key commands is on my list. I was thinking about a solution where e.g. TAB would take you to the next link, Shift-TAB to the previous. Adding rollover to this is a great idea! In addition to navigate from link to link, I'd like to keep the next/previous line navigation (right now arrow-up/down). In addition, I'd like to implement presets for vim and emacs-users, so that `j` equals arrow-down, and `k` arrow up in vim mode. Usual keybindings also include `g` for top of the page and `G` for end of the page. What do you think?

**Comment by kseistrup** [comment]
I rarely use the emacs/vim keys for up/down/left/right myself, but for those who do it's a nice feature. I also like the TAB/Shift-TAB idea!

**Comment by jansc** [comment]
The 'n' (next) and 'p' (previous) keys can now be used to navigate from url to url, with one gotcha - when the selection moves out of the currently visible window, the visible window does not follow the selection. I'll investigate further.
