### ISSUE TITLE
SSL certs not checked for gemini protocol

### ISSUE THREAD

**Issue by vext01** [jansc/ncgopher#6]
Hi again,

I pointed ncgopher at a local gemini server with a self-signed certificate and it didn't complain.

(Bombadillo does complain)

Thanks

**Comment by jansc** [comment]
That's intentional. Bombadillo is wrong ;-)

We discussed this a while ago in the #gemini irc-channel on tilde.chat. Solderpunk encourages the use of self-signed certificates, and many servers use them, so complaining about these certificates does help the user. When a certificate changes, however, ncgopher will issue a warning.

See the gemini-spec, section 4.2: 

> Clients can validate TLS connections however they like (including not at all) but the strongly RECOMMENDED approach is to implement a lightweight "TOFU" certificate-pinning system which treats self-signed certificates as first- class citizens.

**Comment by vext01** [comment]
Well that's one way of doing it I guess.
